{
 "title": "Database Dashboard",
 "time": { "from": "2025-11-03T21:26:33.800Z", "to": "2025-11-06T06:27:04.040Z" },
 "panels": [
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_stat_bgwriter_stats_reset_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - pg_postmaster_start_time_seconds",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Database Size",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{datname=\"postgres\", schemaname=\"classicmodels\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_seq_scan{datname=\"postgres\", schemaname=\"classicmodels\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows in 'payments' table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{datname=\"postgres\", schemaname=\"classicmodels\", relname=\"payments\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows in 'orders' table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{datname=\"postgres\", schemaname=\"classicmodels\", relname=\"orders\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per Second (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"postgres\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Scanned Tables",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(5, sum by (relname) (rate(pg_stat_user_tables_idx_scan{datname=\"postgres\", schemaname=\"classicmodels\"}[5m]) + rate(pg_stat_user_tables_seq_scan{datname=\"postgres\", schemaname=\"classicmodels\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}