{
 "title": "Weather Dashboard (Astana)",
 "description": "External API Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_cloudcover_percent{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_windspeed_kmh{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_wind_direction_degrees{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apparent Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_apparent_temperature_celsius{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_humidity_percent{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snowfall",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_snowfall_cm{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Showers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_showers_mm{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_rain_mm{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}